services:
  # anchor for references
  api: &api
    image: alpha-apartments-api:local-latest
    container_name: alpha_apartments_api
    volumes:
      - .:/app:z
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env.local
    depends_on:
      mailpit:
        condition: service_healthy
      postgres:
        condition: service_healthy
    # shellscript
    command: /start
    networks:
      - alpha_apartments_production_network
  
  postgres:
    image: alpha-postgres-db:local-latest
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - alpha_apartments_db_data:/var/lib/postgresql/data
    env_file:
      - ./.env.local
    networks:
      - alpha_apartments_production_network

  # good for local development, prod should use Mailgun
  mailpit:
    image: alpha-mailpit:local-latest
    restart: unless-stopped
    container_name: mailpit
    healthcheck:
      test: curl http://localhost:8025/readyz -I || exit 1
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - alpha_apartments_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      # unsecure login for dev:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - alpha_apartments_production_network

networks:
  alpha_apartments_production_network:
    external: true

volumes:
  alpha_apartments_db_data: {}
  alpha_apartments_mailpit_data: {}
